TrajectoryPlannerROS:
  max_vel_x: 0.5
  max_vel_theta: 0.3
  min_vel_x: 0.1
  max_rotational_vel: 0.2
  min_in_place_rotational_vel: 0.02
  acc_lim_th: 3.0
  acc_lim_theta: 1.5
  acc_lim_x: 1.5
  acc_lim_y: 1.5
  holonomic_robot: false
  dwa: false
  pdist_scale: 0.6
  gdist_scale: 1.0
  xy_goal_tolerance: 0.0

  

  
DWAPlannerROS:
  max_vel_x: 0.5
  max_vel_theta: 0.2
  min_vel_x: 0.1
  max_vel_y: 0.0
  min_vel_y: 0.0
  xy_goal_tolerance: 0.2
  max_rotational_vel: 0.1
  min_in_place_rotational_vel: 0.02
  acc_lim_th: 1.5
  acc_lim_theta: 1.5
  acc_lim_x: 1.5
  acc_lim_y: 1.5
  forward_point_distance: 0.0
  holonomic_robot: false