TrajectoryPlannerROS:
  ##max_vel_x: 0.5
  ##max_rotational_vel: 0.5
  ##min_in_place_rotational_vel: 0.02
  ##acc_lim_theta: 3.2
  ##acc_lim_x: 2.5
  ##acc_lim_y: 2.5
  ##holonomic_robot: false
  ##pdist_scale: 0.6
  ##gdist_scale: 0.8
  ##xy_goal_tolerance: 0.2
  ##yaw_goal_tolerance: 0.35
  dwa: false

DWAPlannerROS:
  max_vel_x: 0.5
  max_rotational_vel: 0.5
  max_vel_y: 0.0
  min_vel_y: 0.0
  xy_goal_tolerance: 0.3
  yaw_goal_tolerance: 0.2
  min_in_place_rotational_vel: 0.02
  acc_lim_th: 3.2
  acc_lim_x: 2.5
  acc_lim_y: 2.5
  forward_point_distance: 0.0
  holonomic_robot: false
  path_distance_bias: 20.0
  goal_distance_bias: 24.0