#define SYSTEM_ID 1
#define COMP_ID 190
#define SYSTEM_TYPE MAV_TYPE_GROUND_ROVER
#define AUTOPILOT_TYPE MAV_AUTOPILOT_GENERIC
#define SYSTEM_MODE MAV_MODE_FLAG_MANUAL_INPUT_ENABLED
#define CUSTOM_MODE 0
#define SYSTEM_STATE MAV_STATE_ACTIVE
		
